### ISSUE TITLE
security

### ISSUE THREAD

**Issue by iglotov** [ruckus-dj/CWMTBot#1]
Мужиииик, api_key & api_hash из конфига прибей, если они валидны. Вообще, как идея, сюда можно положить config.template со значениями для примера, а реальный конфиг прописать в игноры, чтобы он не заливался.

**Comment by ruckus-dj** [comment]
Благодарю за замечание и за подсказку.
Правда есть вопрос, id и hash можно использовать в любом неофициальном клиенте, коим от части и является эта... эммм... наработка. Как я могу опубликовать "релиз" со встроенными id и hash не выкладывая их в явном виде?

**Comment by iglotov** [comment]
Вот вторая часть комментария и была этому посвящена. Создаётся файл ".gitignore", в котором отдельной строкой указывается config.py, после этого он перестаёт заливаться на гитхаб. А рядом создать config.template, или, как уже сделано, demo_config.py, который нужно будет скопировать и поправить перед фактическим использованием в новом месте. Нужно будет просто упомянуть этот момент в README.md

**Comment by ruckus-dj** [comment]
Я немного не о том. Уже сделал всё как вы предложили, но в будущем планирую публиковать релиз уже со встроенными ключами (если до него, конечно, дойдёт).
Так вот, могу ли я как-то встроить рабочие id, hash в питоне не в открытом виде, а не заставлять пользователя получать свои?
И вообще на сколько это соответствует правилам телеграма?

**Comment by iglotov** [comment]
<img width="733" alt="2017-04-24 14 44 44" src="https://cloud.githubusercontent.com/assets/5945071/25327207/795c8fea-28fd-11e7-8a3b-c026c03c8dd4.png">
Да не похоже, чтобы соответствовало. :) а комбинация id и hash напрямую даёт доступ к аккаунту телеграма, под которым они были созданы.

**Comment by ruckus-dj** [comment]
А как же тогда выкладываются неофициальные клиенты?
То есть если я захочу опубликовать "это" скажем в App Store мне надо будет просить id и hash у пользователя?
Должен же быть способ.

**Comment by iglotov** [comment]
Конечно просить ввести! Это то же самое, что логин и пароль клиента, то есть его учетные данные. Только в случае app store придётся просить логин/пароль, а id/hash нужны для контролируемого доступа отдельного приложения.

**Comment by ruckus-dj** [comment]
Ещё раз, посмотрите, пожалуйста, неофициальные клиенты телеграма. Они не просят id и hash, а значит имеют их уже вшитые. id и hash не логинят пользователя, а лишь идентифицируют клиент, залогиниться я могу под каким угодно аккаунтом с чужими id и hash. И получить доступ к аккаунту имея id и hash невозможно, на сколько я знаю, необходим номер телефона и код авторизации, других вариантов нет.
Ладно, я пока оставлю этот вопрос, до "релиза" ещё долго, других проблем хватает.
Свои данные из исходников выпилил, issue закрываю.
